export const usePortfolioInfo = () => {
	const navBar = {
		items: [
			{ text: 'About', url: '/' },
			{ text: 'Experience', url: '/#experience' },
			{ text: 'Projects', url: '/#projects' },
			{ text: 'Studies', url: '/#studies' },
		],
		logo: '/brand/logo-vertical.png',
		userLogo: '/brand/only-logo-nobg.png',
	}
	const footer = {
		items: [
			{ text: 'About', url: '/' },
			{ text: 'Experience', url: '/#experience' },
			{ text: 'Projects', url: '/#projects' },
			{ text: 'Studies', url: '/#studies' },
		],
		logo: '/brand/logo-vertical.png',
		userLogo: '/brand/only-logo-nobg.png',
	}
	const myInfo = {
		nickName: 'MaRoDev',
		name: 'Maxi Roig',
		occupation: 'Front End developer',
		slogan: 'I build dreams, engaging and accessible digital experiences.',
		image: '/profile.png',
		socials: [
			{
				name: 'Linkedin',
				url: 'https://www.linkedin.com/in/maxi-roig/',
				icon: 'mdi:linkedin',
				id: '1',
			},
			{
				name: 'Github',
				url: 'https://github.com/maxxbit77',
				icon: 'mdi:github',
				id: '2',
			},
		],
		contact: {
			text: 'Copy Email',
			icon: 'ph:download-simple-thin',
			email: 'maxielcade04@gmail.com',
		},
	}
	const experience = [
		{
			projectName: 'Tickets seller',
			companyName: 'Beon WorldWide',
			startAt: '2024',
			endsAt: '2024',
			position: 'Front end Developer',
			description:
				'The ticketing application is an internal web-based platform designed for selling tickets for corporate events. It allows users to purchase tickets and select their seats using SVG map manipulation for enhanced interactivity. The application aims to simplify event management by providing a clear visualization of available seating options.',
			url: 'https://beonworldwide.com/es',
			tags: [
				'JavaScript',
				'TypeScript',
				'Vue.js 3',
				'Nuxt.js 3',
				'Tailwind CSS',
				'Jest',
				'Docker',
				'Git',
				'SCRUM',
				'D3.js',
				'REST API',
			],
			image: {
				url: '/images/experience/mockup-beonWW.png',
				alt: 'mockup Tickets seller',
			},
		},
		{
			projectName: 'Squinbox',
			companyName: 'Mosaiqo S.L.',
			startAt: '2023',
			endsAt: '2024',
			position: 'Front end Developer',
			description:
				'Squinbox is a directory of newsletters where content creators can create their bio profile, so that companies can contact them to advertise within their newsletters.',
			url: 'https://squinbox.com/',
			tags: [
				'Javascript',
				'Vue 3',
				'Nuxt js',
				'TypeScript',
				'Tailwind',
				'FormKit',
				'Prisma',
				'Pinia',
				'Git',
				'Scrum',
				'REST API',
			],
			image: {
				url: '/images/experience/mockup-sq.jpg',
				alt: 'mockup Squinbox',
			},
		},
		{
			projectName: 'Rapid Launch',
			companyName: 'Mosaiqo S.L.',
			startAt: '2023',
			endsAt: '2023',
			position: 'Front end Developer',
			description:
				'RapidLaunch is a boilerplate designed on Vue3 and Nuxt, its function is that anyone, even without extensive programming knowledge, can deploy a website in a matter of minutes. It also includes the main integrations fully configured that a website requires.',
			url: 'https://rapidlaunch.it/',
			tags: [
				'Javascript',
				'Vue 3',
				'Nuxt js',
				'TypeScript',
				'Tailwind',
				'Next-Auth',
				'FormKit',
				'Pinia',
				'VueUse',
				'Node js',
				'Git',
				'Scrum',
				'REST API',
			],
			image: { url: '/images/experience/mockup-rl.jpg', alt: 'mockup RapidLaunch' },
		},
		{
			projectName: 'Horizon Hub',
			companyName: 'Mosaiqo S.L.',
			startAt: '2022',
			endsAt: '2023',
			position: 'Frontend Developer',
			description:
				'HorizonHub is a platform aimed at entrepreneurs or business owners, who can generate through AI, a detailed report of their idea (market study). With this report, a user can decide if their idea is feasible to develop.',
			url: 'https://horizonhub.io/',
			tags: [
				'Javascript',
				'Vue 3',
				'Nuxt js',
				'TypeScript',
				'Tailwind',
				'Vue-final-Modal',
				'Pinia',
				'axios',
				'shurikenUI',
				'webpack',
				'Git',
				'Scrum',
				'REST API',
				'headlessUI',
			],
			image: { url: '/images/experience/mockup-hh.jpg', alt: 'mockup HorizonHub' },
		},
		{
			projectName: 'NFUT Cards',
			companyName: 'Mosaiqo S.L.',
			startAt: '2021',
			endsAt: '2022',
			position: 'Front End Developer',
			description:
				'NFUT Cards was a card combat game with a football theme, inspired by traditional trading card games, where 2 players would battle each other in real-time.',
			url: 'https://twitter.com/nfutcards',
			tags: ['Wordpress', 'Javascript', 'HTML5', 'Css3', 'OAuth', 'ESLint', 'docker'],
			image: { url: '/images/experience/mockup-nfut.jpg', alt: 'mockup NFUTCards' },
		},
	]

	const projects = [
		{
			projectName: 'WorldHaven',
			companyName: 'Training Project',
			startAt: '2020',
			endsAt: '2021',
			position: '',
			description:
				"The book's home is a portal where you can choose the books you like the most and add them to your favorites list to read them whenever you feel like it. This app has filters to make it easier to search for your favorite book.",
			url: 'https://bitbucket.org/maxxbit77dev/wordheaven/src/main/',
			tags: [
				'Javascript',
				'API REST',
				'Vue3',
				'VueUse',
				'Vuex',
				'Axios',
				'Tailwind',
				'cypress',
				'HTML5',
				'Css3',
				'Git',
			],
			image: { url: '/images/projects/mockup-wh.jpg', alt: 'mockup WorldHaven' },
		},
		{
			projectName: 'Rick & Morty APP',
			companyName: 'Training Project',
			startAt: '2020',
			endsAt: '2020',
			description:
				'Created a task manager application with features like task creation, editing, and deletion. Implemented using Vue.js for the frontend and connected to a simple backend for data management.',
			technologies: ['Vue.js', 'Vuex', 'REST API', 'SCSS'],
			url: 'https://bitbucket.org/maxxbit77dev/rick-morty/src/main/',
			tags: ['Javascript', 'Vue 3', 'Vue Router', 'Axios', 'Tailwind', 'cypress', 'Pinia', 'API REST', 'Git'],
			image: { url: '/images/projects/mockup-rm.jpg', alt: 'mockup Rick&Morty' },
		},
	]
	const studies = [
		{
			courseName: 'NodeJS - The Complete Guide',
			author: 'Maximilian Schwarzmuller',
			duration: '40,5',
			lessons: '543',
			rating: 4.6,
			image: { url: '/images/studies/node.jpg', alt: 'Node JS' },
			status: 'In Progress',
			url: 'https://www.udemy.com/course/nodejs-the-complete-guide/',
			tags: [
				'Modules',
				'Requests',
				'Responses',
				'Rendering',
				'Express.js',
				'MVC',
				'Cookies',
				'Auth',
				'SQL',
				'REST',
			],
		},
		{
			courseName: 'Understanding TypeScript',
			author: 'Maximilian Schwarzmuller',
			duration: '15',
			lessons: '198',
			rating: 4.7,
			image: { url: '/images/studies/typescript.jpg', alt: 'TypeScript' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/understanding-typescript/',
			tags: ['Types', 'Classes', 'Interfaces', 'Decorators', 'Namespaces', 'webpack', 'workflow'],
		},
		{
			courseName: 'The Nuxt 3 Bootcamp',
			author: 'Laith Harb',
			duration: '17',
			lessons: '156',
			rating: 4.6,
			image: { url: '/images/studies/nuxt.jpg', alt: 'Nuxt' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/the-nuxt-3-bootcamp-the-complete-developer-guide/',
			tags: ['HTTP requests', 'CSR', 'layouts', 'useAsyncData', 'authentication', 'Supabase', 'useFetch'],
		},
		{
			courseName: 'Vue - The Complete Guide',
			author: 'Maximilian Schwarzmuller',
			duration: '31,5',
			lessons: '331',
			rating: 4.8,
			image: { url: '/images/studies/vue-guide.jpg', alt: 'Vue' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/vuejs-2-the-complete-guide/',
			tags: ['Basics', 'Reactive', 'Events', 'Environments', 'Vuex', 'Http', 'Auth', 'Deploy'],
		},
		{
			courseName: 'JS, HTML, CSS3, NodeJS',
			author: 'Nicolas Schurmann',
			duration: '19',
			lessons: '202',
			rating: 4.6,
			image: { url: '/images/studies/js-html-css-node.jpg', alt: 'js-html-css-node' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/aprende-javascript-es9-html-css3-y-nodejs-desde-cero/',
			tags: ['Js ES9', 'HTML', 'CSS3', 'NodeJS', 'DOM', 'Mongo', 'RESTFUL API'],
		},
		{
			courseName: 'JavaScript Full',
			author: 'Grover Vasquez',
			duration: '16',
			lessons: '174',
			rating: 4.4,
			image: { url: '/images/studies/javascript.jpg', alt: 'javascript' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/javascript-moderno-para-principiantes/',
			tags: ['DOM', 'AJAX', 'APIs', 'Node.js', 'Async', 'this Object'],
		},
		{
			courseName: 'La biblia perdida de Bootstrap',
			author: 'Erick Mines',
			duration: '9,5',
			lessons: '80',
			rating: 4.6,
			image: { url: '/images/studies/bootstrap.jpg', alt: 'bootstrap' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/curso-la-biblia-perdida-de-bootstrap-4/',
			tags: ['HTML5', 'CSS3', 'Mobile First', 'jQuery', 'Responsive design'],
		},
		{
			courseName: 'The Complete jQuery Course',
			author: 'Joe Parys',
			duration: '6',
			lessons: '51',
			rating: 4.5,
			image: { url: '/images/studies/jquery.jpg', alt: 'jquery' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/jquery-tutorial/',
			tags: ['AJAX', 'APIs', 'JS', 'events', 'DOM', 'Github', 'Git'],
		},
	]

	return {
		navBar,
		myInfo,
		experience,
		projects,
		studies,
		footer,
	}
}
