export const usePortfolioInfo = () => {
	const navBar = {
		items: [
			{ text: 'About', url: '/' },
			{ text: 'Experience', url: '/#experience' },
			{ text: 'Projects', url: '/#projects' },
			{ text: 'Studies', url: '/#studies' },
		],
		logo: '/brand/logo-vertical.png',
		userLogo: '/brand/only-logo-nobg.png',
	}
	const footer = {
		items: [
			{ text: 'About', url: '/' },
			{ text: 'Experience', url: '/#experience' },
			{ text: 'Projects', url: '/#projects' },
			{ text: 'Studies', url: '/#studies' },
		],
		logo: '/brand/logo-vertical.png',
		userLogo: '/brand/only-logo-nobg.png',
	}
	const myInfo = {
		nickName: '@maxxbit',
		name: 'Maxi Roig',
		occupation: 'Front-end UI developer',
		slogan: 'Focused on Interactions and Design',
		image: '/profile.png',
		socials: [
			{
				name: 'Linkedin',
				url: 'https://www.linkedin.com/in/maxi-roig/',
				// icon: 'pixelarticons:github',
				id: '1',
			},
			{
				name: 'Github',
				url: 'https://github.com/maxxbit77',
				// icon: 'pixelarticons:github',
				id: '2',
			},
		],
		contact: {
			text: 'Copy Email',
			icon: 'pixelarticons:cloud-download',
			email: 'maxielcade04@gmail.com',
		},
	}
	const experience = [
		{
			projectName: 'BeKultura',
			companyName: 'Beon WorldWide',
			startAt: '2024',
			endsAt: '2024',
			position: 'Front end Developer',
			description:
				'A ticketing platform that enables event organizers to create, and sell tickets for concerts, theater, and other live events. It features secure payment processing, real-time ticket availability, and interactive seat selection. The platform also offers event promotion tools and integration with major marketing channels.',
			responsibilities: [
				'Developed an internal ticketing platform.',
				'Enhanced UX for ticket purchasing.',
				'Developed tools for event management.',
			],
			url: 'https://beonworldwide.com/es',
			tags: ['JS(ES6)', 'TypeScript', 'Vue 3', 'Nuxt 3', 'Tailwind 3', 'Vitest', 'Git', 'D3.js', 'REST API'],
			// image: {
			// 	url: '/images/experience/mockup-beonWW.webp',
			// 	alt: 'mockup Tickets seller',
			// },
			video: 'https://res.cloudinary.com/dw6ikrcqm/video/upload/v1740275588/beon_kps6qr.mp4',
		},
		{
			projectName: 'Squinbox',
			companyName: 'Mosaiqo S.L.',
			startAt: '2023',
			endsAt: '2024',
			position: 'Front end Developer',
			description:
				'Platform designed to connect creators of newsletters. It enables users collaborate with other newsletters to grow together. By registering, creators can add their newsletters to the directory, find others with similar interests, and propose cross-promotions to expand their subscriber base.',
			responsibilities: [
				'Designed an intuitive UI.',
				'Developed user profile system.',
				'Improved performance and loading speed.',
			],
			url: 'https://squinbox.com/',
			tags: ['JS(ES6)', 'Vue 3', 'Nuxt 3', 'TypeScript', 'Tailwind', 'FormKit', 'Prisma', 'Pinia'],
			// image: {
			// 	url: '/images/experience/mockup-sq.webp',
			// 	alt: 'mockup Squinbox',
			// },
			video: 'https://res.cloudinary.com/dw6ikrcqm/video/upload/v1740275596/squinbox_ruhxzv.mp4',
		},
		{
			projectName: 'Rapid Launch',
			companyName: 'Mosaiqo S.L.',
			startAt: '2023',
			endsAt: '2023',
			position: 'Front end Developer',
			description:
				'A startup launch assistant that streamlines the process of creating and deploying new businesses. It provides tools for idea validation, project management, and automated website deployment to accelerate go-to-market strategies.',
			responsibilities: [
				'Developed a Vue 3 & Nuxt-based boilerplate.',
				'Designed setup for non-developers.',
				'Scalability and maintainability.',
			],
			url: 'https://rapidlaunch.it/',
			tags: ['JS(ES6)', 'Vue 3', 'Nuxt 3', 'TypeScript', 'Tailwind', 'Pinia', 'Radix', 'Shadcn', 'Vitest'],
			// image: { url: '/images/experience/mockup-rl.webp', alt: 'mockup RapidLaunch' },
			video: 'https://res.cloudinary.com/dw6ikrcqm/video/upload/v1740275508/rapid-launch_ydnzab.mp4',
		},
		{
			projectName: 'NFUT Cards',
			companyName: 'Mosaiqo S.L.',
			startAt: '2020',
			endsAt: '2021',
			position: 'Front End Developer',
			description:
				'A digital trading card game based on real-world football players. Users can collect, trade, and compete with their NFT-based player cards, with dynamic stats that update based on real match performances.',
			responsibilities: [
				'Designed the website layout and structure.',
				'Implemented responsive design.',
				'Optimized website speed and performance.',
			],
			url: 'https://twitter.com/nfutcards',
			tags: [
				'HTML5',
				'Css3',
				'Block Editor',
				'Elementor',
				'Theme Customization',
				'FSE (Full Site Editing)',
				'UI/UX',
			],
			// image: { url: '/images/experience/mockup-nfut.webp', alt: 'mockup NFUTCards' },
			video: 'https://res.cloudinary.com/dw6ikrcqm/video/upload/v1740275664/nfut_w6ijfd.mp4',
		},
		{
			projectName: 'Horizon Hub',
			companyName: 'Mosaiqo S.L.',
			startAt: '2022',
			endsAt: '2023',
			position: 'Frontend Developer',
			description:
				'A community platform that connects startup founders with early adopters. It allows creators to validate their ideas and receive valuable feedback before launching, while users can discover and influence new innovations from their early stages.',
			responsibilities: [
				"Enhanced the platform's user interface.",
				'Algorithms for idea feasibility assessment.',
				'Optimized the system for quick insights.',
			],
			url: 'https://horizonhub.io/',
			tags: ['JS(ES6)', 'Vue 3', 'Nuxt 3', 'TypeScript', 'Tailwind', 'Pinia', 'axios', 'REST API'],
			// image: { url: '/images/experience/mockup-hh.webp', alt: 'mockup HorizonHub' },
			video: 'https://res.cloudinary.com/dw6ikrcqm/video/upload/v1740275520/horizonhub_dfam9g.mp4',
		},
	]

	const projects = [
		{
			projectName: 'FinancesFlow',
			companyName: 'Project',
			startAt: '2024',
			endsAt: 'Now',
			position: '',
			description:
				'Finance management application that helps users track their bank accounts, cash, investments, and cryptocurrencies. It will provide a clear overview of financial status with interactive charts and real-time market data.',
			url: 'https://github.com/maxxbit77/finance-manager',
			tags: [
				'Bitcoin',
				'Cryptos',
				'Finances',
				'Markets',
				'Wallet',
				'Charts',
				'News',
				'Investments',
				'Stocks',
				'Portfolio',
				'Trading',
				'Analytics',
				'Trends',
			],
		},
		{
			projectName: 'Vibency',
			companyName: 'Project',
			startAt: '2024',
			endsAt: 'Now',
			description:
				'An app where users share their mood on a map using emotes. Post your feelings, explore global emotions in real-time, and connect through a shared emotional experience.',
			technologies: ['Vue.js', 'Vuex', 'REST API', 'SCSS'],
			url: 'https://github.com/maxxbit77/Vibency-frontend-clone',
			tags: ['Real-time Location', 'Emotions', 'Social', 'Map', 'Geolocation', 'Emotes', 'Mood', 'Feelings'],
		},
	]
	const courses = [
		{
			courseName: 'React',
			author: 'Maximilian Schwarzmuller',
			duration: '40,5',
			lessons: '543',
			rating: 4.6,
			image: { url: '/images/studies/react.webp', alt: 'React' },
			status: 'In Progress',
			url: 'https://www.udemy.com/course/nodejs-the-complete-guide/',
			tags: ['Redux', 'Requests', 'Routing', 'Rendering', 'Hooks', 'Testing', 'Auth'],
		},
		{
			courseName: 'NodeJS',
			author: 'Maximilian Schwarzmuller',
			duration: '40,5',
			lessons: '543',
			rating: 4.6,
			image: { url: '/images/studies/node.jpg', alt: 'Node JS' },
			status: 'In Progress',
			url: 'https://www.udemy.com/course/nodejs-the-complete-guide/',
			tags: ['Modules', 'Requests', 'Responses', 'Rendering', 'Express.js', 'Cookies', 'Auth'],
		},
		{
			courseName: 'TypeScript',
			author: 'Maximilian Schwarzmuller',
			duration: '15',
			lessons: '198',
			rating: 4.7,
			image: { url: '/images/studies/typescript.jpg', alt: 'TypeScript' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/understanding-typescript/',
			tags: ['Types', 'Classes', 'Interfaces', 'Decorators', 'Namespaces', 'webpack', 'workflow'],
		},
		{
			courseName: 'Nuxt 3 ',
			author: 'Laith Harb',
			duration: '17',
			lessons: '156',
			rating: 4.6,
			image: { url: '/images/studies/nuxt.jpg', alt: 'Nuxt' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/the-nuxt-3-bootcamp-the-complete-developer-guide/',
			tags: ['HTTP requests', 'CSR', 'layouts', 'useAsyncData', 'authentication', 'Supabase', 'useFetch'],
		},
		{
			courseName: 'Vue 3',
			author: 'Maximilian Schwarzmuller',
			duration: '31,5',
			lessons: '331',
			rating: 4.8,
			image: { url: '/images/studies/vue-guide.jpg', alt: 'Vue' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/vuejs-2-the-complete-guide/',
			tags: ['Basics', 'Reactive', 'Events', 'Environments', 'Vuex', 'Http', 'Auth', 'Deploy'],
		},
		{
			courseName: 'JS, HTML, CSS3, NodeJS',
			author: 'Nicolas Schurmann',
			duration: '19',
			lessons: '202',
			rating: 4.6,
			image: { url: '/images/studies/js-html-css-node.jpg', alt: 'js-html-css-node' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/aprende-javascript-es9-html-css3-y-nodejs-desde-cero/',
			tags: ['Js ES9', 'HTML', 'CSS3', 'NodeJS', 'DOM', 'Mongo', 'RESTFUL API'],
		},
		{
			courseName: 'JavaScript',
			author: 'Grover Vasquez',
			duration: '16',
			lessons: '174',
			rating: 4.4,
			image: { url: '/images/studies/javascript.jpg', alt: 'javascript' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/javascript-moderno-para-principiantes/',
			tags: ['DOM', 'AJAX', 'APIs', 'Node.js', 'Async', 'this Object'],
		},
		{
			courseName: 'Bootstrap',
			author: 'Erick Mines',
			duration: '9,5',
			lessons: '80',
			rating: 4.6,
			image: { url: '/images/studies/bootstrap.jpg', alt: 'bootstrap' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/curso-la-biblia-perdida-de-bootstrap-4/',
			tags: ['HTML5', 'CSS3', 'Mobile First', 'jQuery', 'Responsive design'],
		},
		{
			courseName: 'jQuery',
			author: 'Joe Parys',
			duration: '6',
			lessons: '51',
			rating: 4.5,
			image: { url: '/images/studies/jquery.jpg', alt: 'jquery' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/jquery-tutorial/',
			tags: ['AJAX', 'APIs', 'JS', 'events', 'DOM', 'Github', 'Git'],
		},
	]

	return {
		navBar,
		myInfo,
		experience,
		projects,
		courses,
		footer,
	}
}
