export const usePortfolioInfo = () => {
	const navBar = {
		items: [
			{ text: 'About', url: '/' },
			{ text: 'Experience', url: '/#experience' },
			{ text: 'Projects', url: '/#projects' },
			{ text: 'Studies', url: '/#studies' },
		],
		logo: '/brand/logo-vertical.png',
		userLogo: '/brand/only-logo-nobg.png',
	}
	const footer = {
		items: [
			{ text: 'About', url: '/' },
			{ text: 'Experience', url: '/#experience' },
			{ text: 'Projects', url: '/#projects' },
			{ text: 'Studies', url: '/#studies' },
		],
		logo: '/brand/logo-vertical.png',
		userLogo: '/brand/only-logo-nobg.png',
	}
	const myInfo = {
		nickName: '@maxxbit',
		name: 'Maxi Roig',
		occupation: 'Front-end UI developer',
		slogan: 'Focused in interactions and design',
		image: '/profile.png',
		socials: [
			{
				name: 'Linkedin',
				url: 'https://www.linkedin.com/in/maxi-roig/',
				// icon: 'pixelarticons:github',
				id: '1',
			},
			{
				name: 'Github',
				url: 'https://github.com/maxxbit77',
				// icon: 'pixelarticons:github',
				id: '2',
			},
		],
		contact: {
			text: 'Copy Email',
			icon: 'pixelarticons:cloud-download',
			email: 'maxielcade04@gmail.com',
		},
	}
	const experience = [
		{
			projectName: 'BeKultura',
			companyName: 'Beon WorldWide',
			startAt: '2024',
			endsAt: '2024',
			position: 'Front end Developer',
			responsibilities: [
				'Developed an internal ticketing platform.',
				'Implemented interactive SVG seat selection.',
				'Enhanced UX for ticket purchasing.',
				'Improved app performance and accessibility.',
				'Integrated payment processing.',
				'Developed tools for event management.',
			],
			url: 'https://beonworldwide.com/es',
			tags: [
				'JS(ES6)',
				'TypeScript',
				'Vue 3',
				'Nuxt 3',
				'Tailwind 3',
				'Vitest',
				'Docker',
				'Git',
				'D3.js',
				'REST API',
			],
			image: {
				url: '/images/experience/mockup-beonWW.png',
				alt: 'mockup Tickets seller',
			},
		},
		{
			projectName: 'Squinbox',
			companyName: 'Mosaiqo S.L.',
			startAt: '2023',
			endsAt: '2024',
			position: 'Front end Developer',
			responsibilities: [
				'Designed an intuitive UI.',
				'Features for advertisers and creators.',
				'Developed user profile system.',
				'Ensured responsive and accessible design.',
				'Improved performance and loading speed.',
				'Handled API integration.',
			],
			url: 'https://squinbox.com/',
			tags: ['JS(ES6)', 'Vue 3', 'Nuxt 3', 'TypeScript', 'Tailwind', 'FormKit', 'Prisma', 'Pinia', 'REST API'],
			image: {
				url: '/images/experience/mockup-sq.jpg',
				alt: 'mockup Squinbox',
			},
		},
		{
			projectName: 'Rapid Launch',
			companyName: 'Mosaiqo S.L.',
			startAt: '2023',
			endsAt: '2023',
			position: 'Front end Developer',
			responsibilities: [
				'Developed a Vue 3 & Nuxt-based boilerplate.',
				'Simplified website deployment process.',
				'Optimized performance for fast loading.',
				'Ensured SEO best practices.',
				'Designed setup for non-developers.',
				'Scalability and maintainability.',
			],
			url: 'https://rapidlaunch.it/',
			tags: [
				'JS(ES6)',
				'Vue 3',
				'Nuxt 3',
				'TypeScript',
				'Tailwind',
				'Pinia',
				'Radix',
				'Shadcn',
				'Vitest',
				'REST API',
			],
			image: { url: '/images/experience/mockup-rl.jpg', alt: 'mockup RapidLaunch' },
		},
		{
			projectName: 'Horizon Hub',
			companyName: 'Mosaiqo S.L.',
			startAt: '2022',
			endsAt: '2023',
			position: 'Frontend Developer',
			responsibilities: [
				"Enhanced the platform's user interface.",
				'Developed an AI-powered report generation.',
				'Integrated market analysis tools for ideas.',
				'Algorithms for idea feasibility assessment.',
				'Optimized the system for quick insights.',
				'Ensured accurate data analysis.',
			],
			url: 'https://horizonhub.io/',
			tags: ['JS(ES6)', 'Vue 3', 'Nuxt 3', 'TypeScript', 'Tailwind', 'Pinia', 'axios', 'REST API', 'headlessUI'],
			image: { url: '/images/experience/mockup-hh.jpg', alt: 'mockup HorizonHub' },
		},
		{
			projectName: 'NFUT Cards',
			companyName: 'Mosaiqo S.L.',
			startAt: '2020',
			endsAt: '2021',
			position: 'Front End Developer',
			responsibilities: [
				'Developed website using WordPress.',
				'Designed the website layout and structure.',
				'Integrated user registration and login.',
				'Implemented responsive design.',
				'Optimized website speed and performance.',
				'Ensured smooth user experience.',
			],
			url: 'https://twitter.com/nfutcards',
			tags: [
				'HTML5',
				'Css3',
				'Block Editor',
				'Elementor',
				'Theme Customization',
				'FSE (Full Site Editing)',
				'UI/UX',
			],
			image: { url: '/images/experience/mockup-nfut.jpg', alt: 'mockup NFUTCards' },
		},
	]

	const projects = [
		{
			projectName: 'FinancesFlow',
			companyName: 'Project',
			startAt: '2024',
			endsAt: 'Now',
			position: '',
			description:
				'Personal finance management application that helps users track their bank accounts, cash, investments, and cryptocurrencies. It provides a clear overview of financial status with interactive charts and real-time market data.',
			url: 'https://github.com/maxxbit77/finance-manager',
			tags: [
				'Bitcoin',
				'Cryptos',
				'Finances',
				'Markets',
				'Wallet',
				'Charts',
				'News',
				'Investments',
				'Stocks',
				'Portfolio',
				'Trading',
				'Analytics',
				'Trends',
			],
		},
		{
			projectName: 'Vibency',
			companyName: 'Project',
			startAt: '2024',
			endsAt: 'Now',
			description:
				'An app where users share their mood on a map using emotes. Post your feelings, explore global emotions in real-time, and connect through a shared emotional experience. 📍😊',
			technologies: ['Vue.js', 'Vuex', 'REST API', 'SCSS'],
			url: 'https://github.com/maxxbit77/Vibency-frontend-clone',
			tags: ['Real-time Location', 'Emotions', 'Social', 'Map', 'Geolocation', 'Emotes', 'Mood', 'Feelings'],
		},
	]
	const courses = [
		{
			courseName: 'NodeJS - The Complete Guide',
			author: 'Maximilian Schwarzmuller',
			duration: '40,5',
			lessons: '543',
			rating: 4.6,
			image: { url: '/images/studies/node.jpg', alt: 'Node JS' },
			status: 'In Progress',
			url: 'https://www.udemy.com/course/nodejs-the-complete-guide/',
			tags: [
				'Modules',
				'Requests',
				'Responses',
				'Rendering',
				'Express.js',
				'MVC',
				'Cookies',
				'Auth',
				'SQL',
				'REST',
			],
		},
		{
			courseName: 'Understanding TypeScript',
			author: 'Maximilian Schwarzmuller',
			duration: '15',
			lessons: '198',
			rating: 4.7,
			image: { url: '/images/studies/typescript.jpg', alt: 'TypeScript' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/understanding-typescript/',
			tags: ['Types', 'Classes', 'Interfaces', 'Decorators', 'Namespaces', 'webpack', 'workflow'],
		},
		{
			courseName: 'The Nuxt 3 Bootcamp',
			author: 'Laith Harb',
			duration: '17',
			lessons: '156',
			rating: 4.6,
			image: { url: '/images/studies/nuxt.jpg', alt: 'Nuxt' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/the-nuxt-3-bootcamp-the-complete-developer-guide/',
			tags: ['HTTP requests', 'CSR', 'layouts', 'useAsyncData', 'authentication', 'Supabase', 'useFetch'],
		},
		{
			courseName: 'Vue - The Complete Guide',
			author: 'Maximilian Schwarzmuller',
			duration: '31,5',
			lessons: '331',
			rating: 4.8,
			image: { url: '/images/studies/vue-guide.jpg', alt: 'Vue' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/vuejs-2-the-complete-guide/',
			tags: ['Basics', 'Reactive', 'Events', 'Environments', 'Vuex', 'Http', 'Auth', 'Deploy'],
		},
		{
			courseName: 'JS, HTML, CSS3, NodeJS',
			author: 'Nicolas Schurmann',
			duration: '19',
			lessons: '202',
			rating: 4.6,
			image: { url: '/images/studies/js-html-css-node.jpg', alt: 'js-html-css-node' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/aprende-javascript-es9-html-css3-y-nodejs-desde-cero/',
			tags: ['Js ES9', 'HTML', 'CSS3', 'NodeJS', 'DOM', 'Mongo', 'RESTFUL API'],
		},
		{
			courseName: 'JavaScript Full',
			author: 'Grover Vasquez',
			duration: '16',
			lessons: '174',
			rating: 4.4,
			image: { url: '/images/studies/javascript.jpg', alt: 'javascript' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/javascript-moderno-para-principiantes/',
			tags: ['DOM', 'AJAX', 'APIs', 'Node.js', 'Async', 'this Object'],
		},
		{
			courseName: 'La biblia perdida de Bootstrap',
			author: 'Erick Mines',
			duration: '9,5',
			lessons: '80',
			rating: 4.6,
			image: { url: '/images/studies/bootstrap.jpg', alt: 'bootstrap' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/curso-la-biblia-perdida-de-bootstrap-4/',
			tags: ['HTML5', 'CSS3', 'Mobile First', 'jQuery', 'Responsive design'],
		},
		{
			courseName: 'The Complete jQuery Course',
			author: 'Joe Parys',
			duration: '6',
			lessons: '51',
			rating: 4.5,
			image: { url: '/images/studies/jquery.jpg', alt: 'jquery' },
			status: 'Completed',
			url: 'https://www.udemy.com/course/jquery-tutorial/',
			tags: ['AJAX', 'APIs', 'JS', 'events', 'DOM', 'Github', 'Git'],
		},
	]

	return {
		navBar,
		myInfo,
		experience,
		projects,
		courses,
		footer,
	}
}
