export const usePortfolioEN = () => {
	const navBar = {
		items: [
			{ text: 'Experience', url: '/#experience' },
			{ text: 'Projects', url: '/#projects' },
			{ text: 'Stack', url: '/#stack' },
			{ text: 'Studies', url: '/#studies' },
		],
		logo: '/brand/logo-vertical.png',
		userLogo: '/brand/only-logo-nobg.png',
	}
	const footer = {
		items: [
			{ text: 'About', url: '/' },
			{ text: 'Experience', url: '/#experience' },
			{ text: 'Projects', url: '/#projects' },
			{ text: 'Studies', url: '/#studies' },
		],
		logo: '/brand/logo-vertical.png',
		userLogo: '/brand/only-logo-nobg.png',
	}
	const myInfo = {
		nickName: '@maxxbit',
		name: 'Maxi Roig',
		occupation: 'Front-end UI developer',
		slogan: 'Focused on Interactions and Design',
		presentation: {
			firstParagraph:
				'I build fast, intuitive apps that feel like a natural extension of your mind, using thoughtful motion designto create fluid, seamless interfaces.',
			firstParagraphhighlighted: '',
			secondParagraph: '',
			secondParagraphhighlighted: 'I bridge the gap between design and engineering',
			thirdParagraph: ', ensuring your product gets the extra attention to detail it needs to',
			thirdParagraphhighlighted: 'stand out from competitors. 🚀',
		},
		image: '/profile.png',
		socials: [
			{
				name: 'Linkedin',
				url: 'https://www.linkedin.com/in/maxi-roig/',
				// icon: 'pixelarticons:github',
				id: '1',
			},
			{
				name: 'Github',
				url: 'https://github.com/maxxbit77',
				// icon: 'pixelarticons:github',
				id: '2',
			},
		],
		contact: {
			wantToChat: 'Want to chat?',
			copyEmail: 'Copy email to clipboard',
			sendEmail: 'Send Email',
			whatsapp: 'WhatsApp chat',
			defaultDescription: 'Send me an email',
			stalkMe: 'STALK ME HERE 👀',
			readCV: 'Read CV',
			text: 'Copy Email',
			icon: 'pixelarticons:cloud-download',
			email: 'maxielcade04@gmail.com',
		},
	}
	const experience = {
		title: 'XP Gained 🎮',
		show: {
			more: 'Show more >>',
			less: '<< Show less',
		},

		list: [
			{
				projectName: 'BeKultura',
				companyName: 'Beon WorldWide',
				startAt: '2024',
				endsAt: '2025',
				position: 'Front end Developer',
				description:
					'Developed a ticketing sales application for corporate events from scratch up to version 1. The application allows users to select seats from multiple SVG-based event maps, add tickets to the cart, and complete the purchase through a payment gateway.',
				responsibilities: [
					'Implemented a user management system.',
					'Used the Singleton pattern and Pinia for state centralization.',
					'Designed and implemented a shopping cart system for ticket purchases and payments.',
					'Centralized error handling and mapping for API responses.',
					'Conducted unit and integration testing to ensure application reliability.',
					'Designed and implemented SVG-based event selection system.',
					'Contributed to the development of the API’s data structure.',
					'Implemented TypeScript to improve code maintainability and reduce errors.',
				],
				url: 'https://beonworldwide.com/es',
				tags: ['JS(ES6)', 'TypeScript', 'Vue 3', 'Nuxt 3', 'Tailwind 3', 'Vitest', 'Git', 'D3.js', 'REST API'],
				// image: {
				// 	url: '/images/experience/mockup-beonWW.webp',
				// 	alt: 'mockup Tickets seller',
				// },
				video: 'https://res.cloudinary.com/dw6ikrcqm/video/upload/v1740275588/beon_kps6qr.mp4',
			},
			{
				projectName: 'Squinbox',
				companyName: 'Mosaiqo S.L.',
				startAt: '2023',
				endsAt: '2024',
				position: 'Front end Developer',
				description:
					'Platform designed to connect creators of newsletters. It enables users collaborate with other newsletters to grow together. By registering, creators can add their newsletters to the directory, find others with similar interests, and propose cross-promotions to expand their subscriber base.',
				responsibilities: [
					'Developed a responsive and visually engaging website.',
					'End-to-end strong typing to ensure agile development.',
					'Configured SSR to maximize SEO performance.',
					'Used a component-based architecture.',
					'Created reusable native Vue 3 components.',
					'Integrated third-party libraries for optimal site functionality.',
					'Handled errors and implemented data mapping.',
					'Conducted unit and integration testing.',
				],
				url: 'https://squinbox.com/',
				tags: ['JS(ES6)', 'Vue 3', 'Nuxt 3', 'TypeScript', 'Tailwind', 'FormKit', 'Prisma', 'Pinia'],
				// image: {
				// 	url: '/images/experience/mockup-sq.webp',
				// 	alt: 'mockup Squinbox',
				// },
				video: 'https://res.cloudinary.com/dw6ikrcqm/video/upload/v1740275596/squinbox_ruhxzv.mp4',
			},
			{
				projectName: 'Rapid Launch',
				companyName: 'Mosaiqo S.L.',
				startAt: '2023',
				endsAt: '2023',
				position: 'Desarrollador Frontend',
				description:
					'Una plantilla de inicio completamente configurable dirigida a emprendedores que buscan lanzar rápidamente una landing page. La plantilla cuenta con un sistema de componentes modulares, permitiendo a los usuarios agregar o eliminar secciones sin esfuerzo. También integra una amplia variedad de bibliotecas de terceros, permitiendo la personalización desde un único archivo de configuración y optimizando el proceso de desarrollo.',
				responsibilities: [
					'Integración de bibliotecas para manejo de errores, múltiples pasarelas de pago, analíticas y más.',
					'Creación de componentes nativos y dinámicos.',
					'Desarrollo de un entorno de pruebas en Nuxt para el despliegue de la plantilla.',
					'Implementación de una arquitectura centralizada utilizando composables.',
					'Diseño de un sistema modular para facilitar la adición o eliminación de componentes.',
					'Documentación del proyecto para una configuración y personalización amigable para el usuario.',
				],
				url: 'https://rapidlaunch.it/',
				tags: ['JS(ES6)', 'Vue 3', 'Nuxt 3', 'TypeScript', 'Tailwind', 'Pinia', 'Radix', 'Shadcn', 'Vitest'],
				// image: { url: '/images/experience/mockup-rl.webp', alt: 'mockup RapidLaunch' },
				video: 'https://res.cloudinary.com/dw6ikrcqm/video/upload/v1740275508/rapid-launch_ydnzab.mp4',
			},
			{
				projectName: 'NFUT Cards',
				companyName: 'Mosaiqo S.L.',
				startAt: '2020',
				endsAt: '2021',
				position: 'Desarrollador Frontend',
				description:
					'Un juego de cartas coleccionables basado en NFT con integración Web3. El juego cuenta con un mazo único de cartas coleccionables respaldadas por tecnología blockchain, permitiendo a los jugadores intercambiar, comprar y vender cartas de manera segura. Se implementó una conexión fluida con billeteras Web3 para autenticación y transacciones, garantizando una experiencia de usuario óptima dentro del ecosistema cripto.',
				responsibilities: [
					'Desarrollo de la interfaz de creación de equipos con funcionalidad de arrastrar y soltar.',
					'Construcción del sitio web con integración Web3 para la gestión de usuarios.',
					'Colaboración en el desarrollo del sistema de combate en tiempo real utilizando WebSockets.',
					'Asistencia en el desarrollo del sistema de pagos basado en tokens.',
					'Optimización de la UI/UX para mejorar la experiencia del jugador.',
					'Integración de interacciones con contratos inteligentes NFT para la propiedad e intercambio de cartas.',
				],
				url: 'https://twitter.com/nfutcards',
				tags: ['HTML5', 'Css3', 'Vue 3', 'Nuxt 3', 'Web sockets', 'Web 3', 'UI/UX'],
				// image: { url: '/images/experience/mockup-nfut.webp', alt: 'mockup NFUTCards' },
				video: 'https://res.cloudinary.com/dw6ikrcqm/video/upload/v1740275664/nfut_w6ijfd.mp4',
			},
			{
				projectName: 'Horizon Hub',
				companyName: 'Mosaiqo S.L.',
				startAt: '2022',
				endsAt: '2023',
				position: 'Desarrollador Frontend',
				description:
					'Una plataforma comunitaria que conecta a fundadores de startups con sus primeros usuarios. Permite a los creadores validar sus ideas y recibir retroalimentación valiosa antes del lanzamiento, mientras que los usuarios pueden descubrir e influir en nuevas innovaciones desde sus primeras etapas.',
				responsibilities: [
					'Mejorar la interfaz de usuario de la plataforma.',
					'Desarrollo de algoritmos para evaluar la viabilidad de ideas.',
					'Optimización del sistema para ofrecer insights rápidos.',
					'Desarrollo de un sitio web responsivo y visualmente atractivo.',
					'Implementación de tipado fuerte de extremo a extremo para garantizar un desarrollo ágil.',
					'Configuración de SSR para maximizar el rendimiento SEO.',
				],
				url: 'https://horizonhub.io/',
				tags: ['JS(ES6)', 'Vue 3', 'Nuxt 3', 'TypeScript', 'Tailwind', 'Pinia', 'axios', 'REST API'],
				// image: { url: '/images/experience/mockup-hh.webp', alt: 'mockup HorizonHub' },
				video: 'https://res.cloudinary.com/dw6ikrcqm/video/upload/v1740275520/horizonhub_dfam9g.mp4',
			},
		],
	}
	const projects = {
		title: "What's cooking? ⏲️",
		soon: 'Soon',
		list: [
			{
				projectName: 'FinancesFlow',
				companyName: 'Project',
				startAt: '2024',
				endsAt: 'Now',
				position: '',
				description:
					'Finance management application that helps users track their bank accounts, cash, investments, and cryptocurrencies. It will provide a clear overview of financial status with interactive charts and real-time market data.',
				url: 'https://github.com/maxxbit77/finance-manager',
				tags: [
					'Bitcoin',
					'Cryptos',
					'Finances',
					'Markets',
					'Wallet',
					'Charts',
					'News',
					'Investments',
					'Stocks',
					'Portfolio',
					'Trading',
					'Analytics',
					'Trends',
				],
			},
			{
				projectName: 'Vibency',
				companyName: 'Project',
				startAt: '2024',
				endsAt: 'Now',
				description:
					'An app where users share their mood on a map using emotes. Post your feelings, explore global emotions in real-time, and connect through a shared emotional experience.',
				technologies: ['Vue.js', 'Vuex', 'REST API', 'SCSS'],
				url: 'https://github.com/maxxbit77/Vibency-frontend-clone',
				tags: ['Real-time Location', 'Emotions', 'Social', 'Map', 'Geolocation', 'Emotes', 'Mood', 'Feelings'],
			},
		],
	}
	const stack = {
		title: 'The tech shelf 📚',
		skill: 'Skill',
	}
	const courses = {
		title: 'LEVEL UP ACADEMY 🏆',
		list: [
			{
				courseName: 'React',
				author: 'Maximilian Schwarzmuller',
				duration: '40,5',
				lessons: '543',
				rating: 4.6,
				image: { url: '/images/studies/react.webp', alt: 'React' },
				status: 'In Progress',
				url: 'https://www.udemy.com/course/nodejs-the-complete-guide/',
				tags: ['Redux', 'Requests', 'Routing', 'Rendering', 'Hooks', 'Testing', 'Auth'],
			},
			{
				courseName: 'NodeJS',
				author: 'Maximilian Schwarzmuller',
				duration: '40,5',
				lessons: '543',
				rating: 4.6,
				image: { url: '/images/studies/node.jpg', alt: 'Node JS' },
				status: 'In Progress',
				url: 'https://www.udemy.com/course/nodejs-the-complete-guide/',
				tags: ['Modules', 'Requests', 'Responses', 'Rendering', 'Express.js', 'Cookies', 'Auth'],
			},
			{
				courseName: 'TypeScript',
				author: 'Maximilian Schwarzmuller',
				duration: '15',
				lessons: '198',
				rating: 4.7,
				image: { url: '/images/studies/typescript.jpg', alt: 'TypeScript' },
				status: 'Completed',
				url: 'https://www.udemy.com/course/understanding-typescript/',
				tags: ['Types', 'Classes', 'Interfaces', 'Decorators', 'Namespaces', 'webpack', 'workflow'],
			},
			{
				courseName: 'Nuxt 3 ',
				author: 'Laith Harb',
				duration: '17',
				lessons: '156',
				rating: 4.6,
				image: { url: '/images/studies/nuxt.jpg', alt: 'Nuxt' },
				status: 'Completed',
				url: 'https://www.udemy.com/course/the-nuxt-3-bootcamp-the-complete-developer-guide/',
				tags: ['HTTP requests', 'CSR', 'layouts', 'useAsyncData', 'authentication', 'Supabase', 'useFetch'],
			},
			{
				courseName: 'Vue 3',
				author: 'Maximilian Schwarzmuller',
				duration: '31,5',
				lessons: '331',
				rating: 4.8,
				image: { url: '/images/studies/vue-guide.jpg', alt: 'Vue' },
				status: 'Completed',
				url: 'https://www.udemy.com/course/vuejs-2-the-complete-guide/',
				tags: ['Basics', 'Reactive', 'Events', 'Environments', 'Vuex', 'Http', 'Auth', 'Deploy'],
			},
			{
				courseName: 'JS, HTML, CSS3, NodeJS',
				author: 'Nicolas Schurmann',
				duration: '19',
				lessons: '202',
				rating: 4.6,
				image: { url: '/images/studies/js-html-css-node.jpg', alt: 'js-html-css-node' },
				status: 'Completed',
				url: 'https://www.udemy.com/course/aprende-javascript-es9-html-css3-y-nodejs-desde-cero/',
				tags: ['Js ES9', 'HTML', 'CSS3', 'NodeJS', 'DOM', 'Mongo', 'RESTFUL API'],
			},
			{
				courseName: 'JavaScript',
				author: 'Grover Vasquez',
				duration: '16',
				lessons: '174',
				rating: 4.4,
				image: { url: '/images/studies/javascript.jpg', alt: 'javascript' },
				status: 'Completed',
				url: 'https://www.udemy.com/course/javascript-moderno-para-principiantes/',
				tags: ['DOM', 'AJAX', 'APIs', 'Node.js', 'Async', 'this Object'],
			},
			{
				courseName: 'Bootstrap',
				author: 'Erick Mines',
				duration: '9,5',
				lessons: '80',
				rating: 4.6,
				image: { url: '/images/studies/bootstrap.jpg', alt: 'bootstrap' },
				status: 'Completed',
				url: 'https://www.udemy.com/course/curso-la-biblia-perdida-de-bootstrap-4/',
				tags: ['HTML5', 'CSS3', 'Mobile First', 'jQuery', 'Responsive design'],
			},
			{
				courseName: 'jQuery',
				author: 'Joe Parys',
				duration: '6',
				lessons: '51',
				rating: 4.5,
				image: { url: '/images/studies/jquery.jpg', alt: 'jquery' },
				status: 'Completed',
				url: 'https://www.udemy.com/course/jquery-tutorial/',
				tags: ['AJAX', 'APIs', 'JS', 'events', 'DOM', 'Github', 'Git'],
			},
		],
	}

	return {
		navBar,
		myInfo,
		experience,
		projects,
		stack,
		courses,
		footer,
	}
}
